[project]
name = "genshin-tools-scripts"
version = "0.1.0"
description = "Scripts for Genshin Tools"
requires-python = ">=3.13"
dependencies = [
    "playwright>=1.49.0",
    "requests>=2.31.0",
    "beautifulsoup4>=4.12.2",
]

[dependency-groups]
dev = [
    "pyright>=1.1.407",
]
